# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clowder_account', '0005_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clowderuser',
            name='allow_email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
