# Generated by Django 2.0.6 on 2018-07-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clowder_account', '0006_clowderuser_allow_email_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clowderuser',
            name='allow_email_notifications',
        ),
    ]
