# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clowder_account', '0005_company_name'),
        ('clowder_server', '0004_ping_public'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='alert',
            index_together=set([('company', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='ping',
            index_together=set([('company', 'name')]),
        ),
    ]
