# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clowder_server', '0006_auto_20170504_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
