# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clowder_server', '0008_auto_20170927_2120'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='clowder_ser_company_83dc78_idx',
        ),
        migrations.AddIndex(
            model_name='ping',
            index=models.Index(fields=['company', 'name', '-create'], name='clowder_ser_company_75820d_idx'),
        ),
    ]
