# Generated by Django 2.0.6 on 2018-07-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clowder_server', '0009_auto_20170927_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
